fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    profiles: https://github.com:mirantis/profiles.git
    roles: https://github.com:mirantis/roles.git
  symlinks:
    roles: "#{source_dir}"
